config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  get '/' => 'homes#top'

  post 'comments/:post_id/create' => 'comments#create'
  post 'comments/:id/update' => 'comments#update'
  post 'comments/:id/destroy' =>'comments#destroy'
  get 'comments/:id/edit' => 'comments#edit'


  post 'likes/:post_id/create' => 'likes#create'
  post 'likes/:post_id/destroy' => 'likes#destroy'
  
  post 'posts/create' => 'posts#create'
  post 'posts/:id/destroy' => 'posts#destroy'
  post 'posts/:id/update' => 'posts#update'
  get 'posts/:id/edit' => 'posts#edit'
  get 'posts/new' => 'posts#new'
  get 'posts/index' => 'posts#index'
  get 'posts/serch' => 'posts#serch'
  get 'posts/:id' => 'posts#show'

  get 'login' => 'users#login_form'
  post 'login' => 'users#login'
  post 'logout' => 'users#logout'
  post  'signup' => 'users#create'
  get 'signup' => 'users#new'

  get 'users/index' => 'users#index'
  get 'users/:id' => 'users#show'
  get 'users/:id/edit' => 'users#edit'
  get 'users/:id/likes' => 'users#likes'
  post 'users/:id/update' => 'users#update'
  post 'users/:id/delete' => 'users#delete'


  resources :users do
    resources :relationships, only:[:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end

end

app/models/user.rb
class User < ApplicationRecord
has_secure_password
validates :introduction, length: {maximum: 250}
validates :name, presence: true
validates :email, presence: true ,uniqueness: true, format: {with: /@/,message:"不正なメールアドレスです"}
validates :password_digest, presence: true

    has_many :posts, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy

    has_many :relationships, foreign_key: :following_id
    has_many :followings, through: :relationships, source: :follower

    has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id
    has_many :followers, through: :reverse_of_relationships, source: :following

    def is_followed_by?(user)
        reverse_of_relationships.find_by(following_id: user.id).present?
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_user
  before_action :authenticate_user,{only:[:edit, :update, :index, :show]}
  before_action :ensure_correct_user,{only:[:edit, :update, :delete]}
  before_action :forbid_login_user,{only:[:new, :create, :login_form, :login]}
  def new
    @user = User.find_by(id: params[:id])
  end

  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      password_digest: params[:password],
      profiel_image: "default_user.jpg"
    )
      if params[:password] == params[:password2] && @user.save
        session[:user_id] = @user.id
        flash[:notice] ="ユーザー登録に成功しました"
        redirect_to("/posts/index")
      elsif params[:name].blank? 
        flash[:alert] = "ユーザー名を登録してください"
        redirect_to("/signup")
      elsif params[:email].blank?
        flash[:alert] = "メールアドレスを登録してください"
        redirect_to("/signup")
      elsif params[:password].blank?
        flash[:alert] = "パスワードを登録してください"
        redirect_to("/signup")
      elsif params[:password] != params[:password2]
        flash[:alert] = "パスワードとパスワード確認が一致しません"
        redirect_to("/signup")
      end
      @user.save
  end
  
  def show
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: params[:id])
    # @post_data = Post.where(user_id: params[:id])
    # @posts = Kaminari.paginate_array(@post_data).page(params[:page]).per(6)
    @posts = Post.where(user_id: params[:id])
  end
  def likes
    @user = User.find_by(id: params[:id])
    @posts = Post.where(user_id: params[:id])
    @likes = Like.where(user_id: params[:id])
  end
  def login_form
  end

  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.password_digest == params[:password]
      session[:user_id] = @user.id
      flash[:notice] = "ログインに成功しました"
      redirect_to("/users/#{@user.id}")
    elsif !@user
      flash[:alert] = "メールアドレスが間違っています"
      redirect_to("/login")
    elsif @user.password != params[:password]
      flash[:alert] = "パスワードが間違っています"
      redirect_to("/login")
    end

  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトに成功しました"
    redirect_to("/")
  end

  def index
    if params[:serch] == nil || params[:serch] == ""
      @users = User.where.not(id: @current_user).order(name: :DESC)
    else
      @users = User.where("name LIKE ?" , "%#{params[:serch]}%")
    end
  
  end

  def edite
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    puts @user.name
    @user.name = params[:name]
    @user.email = params[:email]
    @user.introduction = params[:introduction]

    if params[:profiel_image]
      @user.profiel_image = "#{@user.id}.jpg"
      image = params[:profiel_image]
      File.binwrite("public/user_images/#{@user.profiel_image}" , params[:profiel_image].read)
    end

    if @user.save
      flash[:notice] = "編集が完了しました!"
      redirect_to("/users/#{@user.id}")
    else
      flash[:alert] = "更新できませんでした"
      redirect_to("/users/#{@user.id}/edit")
    end
  end

  def delete
    @user = User.find_by(id: @current_user.id)
    @user.destroy
    redirect_to ("/")
  end

  def followings
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: params[:id])
    @posts = Post.where(user_id: params[:id])
    user = User.find(params[:id])
    @users = user.followings
  end
  
  def followers
    @user = User.find_by(id: params[:id])
    @posts = Post.where(user_id: params[:id])
    @likes = Like.where(user_id: params[:id])
    user = User.find(params[:id])
    @users = user.followers
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    if @current_user != @user
      flash[:notice] = "権限がありません"
      redirect_to request.referrer || "/posts/index"
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profiel.html.erb
<div class="show-profiel">
    <div class="show-profiel-line">
        <div class="show-profiel-image">
            <img src="<%= "/user_images/#{@user.profiel_image}"%>">
        </div>
        <% if @user == @current_user %>
            <div class="setting-image">
                <%= link_to image_tag("setting.png"),"/users/#{@user.id}/edit" %>
            </div>
            <div class="logout-button">
                <%= button_to image_tag("logout.png") , "/logout" %>
            </div>
        <% end %>
        <%# フォロー・リム－ブボタン %>
        <% if @user != @current_user %>
            <div class="follow-unfollow">
                <% if @user.is_followed_by?(@current_user) %>
                    <%= button_to("フォロー解除",user_relationship_path(@user),  {method: :delete, class: "unfollow-btn"}) %>
                <% else %>
                    <%= button_to("フォロー",user_relationships_path(@user), class: "follow-btn")%>
                <% end %>
            </div>
        <% end %>
    </div>
    <h3 class="profiel-name"><%= @user.name %></h3>
    <p class="user-introduction"><%= safe_join(@user.introduction.to_s.split("\n"),tag(:br)) %></p>
    <div class="profiel-under-container">
        <%= link_to "投稿#{@posts.length}件", "/users/#{@user.id}", class:"no-mergin"%>
        <%= link_to "いいね#{@likes.length}件", "/users/#{@user.id}/likes"%>
        <%= link_to "フォロー#{@user.followings.count}人", followings_user_path(@user) %>
        <%= link_to "フォロワー#{@user.followers.count}人", followers_user_path(@user) %>
    </div>
</div>

app/views/users/edit.html.erb
<%# プレビュー機能 %>
<script>
    (()=>{
        document.addEventListener('DOMContentLoaded', () => {
            const createImageHTML = (blob) => {
            const imageElement = document.getElementById('edit-image');
            const blobImage = document.createElement('img');
            blobImage.setAttribute('class', 'edit-img')
            blobImage.setAttribute('src', blob);

            imageElement.appendChild(blobImage);
            };

            document.getElementById('user-img').addEventListener('change', (e) => {
            const imageContent = document.querySelector('.edit-img');
            if (imageContent){
                imageContent.remove();
            }

            const file = e.target.files[0];
            const blob = window.URL.createObjectURL(file);
            createImageHTML(blob);
            });
        });
    })();
</script>

<%# 編集ページ %>
<div class="profiel-edit">
    <div class="title-container">
        <h1 class="page-title">ユーザー編集</h1>
        <%= button_to image_tag("trash.png"),"/users/#{@user.id}/delete", class:"delete-btn"%>
    </div>
    <%= form_tag("/users/#{@user.id}/update" , {multipart:true}) do %> 
        <div class="profiel-container">
            <div class="edit-left">
                <p>ユーザー名</p>
                <p> メールアドレス</p>
                <p>プロフィール</p>
                <p class="edit-img-p">画像</p>
            </div>
            <div class="edit-right">
                <input name="name" value="<%= @user.name %>" class="user-name">
                <br>
                <input name="email" value="<%= @user.email %>" class="user-email">
                <br>
                <textarea name="introduction" class="user-body"><%= @user.introduction %></textarea>
                <br>
                <input name="profiel_image" type="file" class="user-picture" id="user-img">
            </div>
        </div>
        <div id="edit-image" class="img-cont"><img class="edit-img" src="/user_images/<%= @user.profiel_image %>"></div>
        <br>
        <div class="submit-container">
            <input type="submit" value="更新" class="user-submit">
        </div>
    <% end %>
</div>

app/views/users/followers.html.erb
<%= render "profiel" %>
<h2 class="profiel-posts-title">フォロワー</h2>
<div class="users-follow-index">
    <% @users.each do |user| %>
        <%= link_to "/users/#{user.id}" do %>
            <div class="user-cont">
                <div class= "user-img">
                    <%= image_tag("/user_images/#{user.profiel_image}") %>
                </div>
                <div class="prof-sentence">
                    <h4 class="user-name"><%= user.name %></h4>
                    <p class="user-introduction"><%= safe_join(user.introduction.to_s.split("\n"),tag(:br)) %></p>
                </div>
            </div>
        <% end %>
    <% end%>
</div>

app/views/users/followings.html.erb
<%= render "profiel" %>
<h2 class="profiel-posts-title">フォロー</h2>
<div class="users-follow-index">
    <% @users.each do |user| %>
        <%= link_to "/users/#{user.id}" do %>
            <div class="user-cont">
                <div class= "user-img">
                    <%= image_tag("/user_images/#{user.profiel_image}") %>
                </div>
                <div class="prof-sentence">
                    <h4 class="user-name"><%= user.name %></h4>
                    <p class="user-introduction"><%= safe_join(user.introduction.to_s.split("\n"),tag(:br)) %></p>
                </div>
            </div>
        <% end %>
    <% end%>
</div>

app/views/users/index.html.erb
<div class="user-serch-form">
    <h1 class="page-title">ユーザー一覧</h1>
    <div class="serch-form">
        <%= form_tag("/users/index" , method: :get) do %>
            <input name="serch" class="serch-indent">
            <input type="submit" value="検索" class="submit-btn">
        <% end %>
    </div>
</div>
<div class="users-index">
    <% @users.each do |user| %>
        <%= link_to "/users/#{user.id}" do %>
            <div class="user-cont">
                <div class= "user-img">
                    <%= image_tag("/user_images/#{user.profiel_image}") %>
                </div>
                <div class="prof-sentence">
                    <h4 class="user-name"><%= user.name %></h4>
                    <p class="user-introduction"><%= safe_join(user.introduction.to_s.split("\n"),tag(:br)) %></p>
                </div>
            </div>
        <% end %>
    <% end%>
</div>

app/views/users/likes.html.erb
<%= render "profiel" %>
<h2 class="profiel-posts-title">いいね</h2>
<div class="profiel-posts">
    <div class="show-tab-content">
        <% @likes.each do |like| %>
            <div class="show-post-body">
                <%= link_to image_tag("/post_images/#{like.post_id}.jpg") , "/posts/#{like.post_id}" %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/login_form.html.erb
<div class="login-form">
    <h2 class="login-logo">ログイン</h2>
    <div class="form-body">
        <% if @error_message %>
            <div class="error-message">
                <%= @error_message %>
            </div>
        <% end%>
        <div class="login-input">
            <%= form_tag('/login') do %>
                <p class="form-label">メールアドレス</p>
                <input name='email' value="<%= @email %>" class="form-input">
                <p class="form-label">パスワード</p>  
                <input name='password' type='password' value="<%= @password %>" class="form-input">
                <br>
                <input type='submit' value="ログイン" class="form-submit">
            <% end%>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="login-form">
    <h2 class="login-logo">新規登録</h2>
    <div class="form-body">
        <% if @error_message %>
            <div class="error-message">
                <%= @error_message %>
            </div>
        <% end%>
        <div class="login-input">
            <%= form_tag("/signup") do%>
                <p class="form-label">ユーザー名</p>
                <input name="name" class="form-input" id="name" value="<%= params[:name]%>">
                <p class="form-label">メールアドレス</p>
                <input name="email" class="form-input" value="<%= @email %>">
                <p class="form-label" class="form-input">パスワード</p>
                <input name="password" type="password" class="form-input">
                <p class="form-label">パスワード確認</p>
                <input name="password2" type="password" class="form-input">
                <br>
                <input type="submit" value="登録" class="form-submit">
            <% end%>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= render "profiel" %>
<h2 class="profiel-posts-title">投稿</h2>
<div class="profiel-posts">
    <div class="show-tab-content show-scroll-list show-jscroll" >
        <% @posts.each do |post| %>
            <div class="show-post-body">
                <%= link_to image_tag("/post_images/#{post.image}") , "/posts/#{post.id}" %>
            </div>
        <% end %>

    </div>
</div>

<%# 無限スクロール機能 %>
<%# <script type="text/javascript">
$(document).ready(function() {
        $('.show-jscroll').jscroll({
            contentSelector: '.show-scroll-list',
            nextSelector: 'span.next:last a'
        });
});
</script>
<h6>jQuery稼働テスト</h6>
<script type="text/javascript">
    $(document).ready(function() {
        $("h6").text("");
    });
</script> %>